// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgtelagisrnnmhplibjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndGVsYWdpc3Jubm1ocGxpYmp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODg5MjEsImV4cCI6MjA3MDQ2NDkyMX0.xnH7YzEsTPvew3iMCx9XVHD59ctgKe3lVw-6mt7rXV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});